Pinfinity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import reverse_lazy
from users.views import CustomPasswordResetView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('content.urls')),
    path('profile/', include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('reset-password/', CustomPasswordResetView.as_view(), name='reset_password'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', CustomPasswordResetCompleteView.as_view(
        template_name='users/reset_password_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from .views import ContentHome, ShowPost, ContentCategory, \
    AddPost, FAQ, SelectAnswer, saved_add, saved_remove, \
    AddComment, AskQuestions, like, remove_like, delete_post

urlpatterns = [
    path('', ContentHome.as_view(), name='index'),
    path('post/<slug:post_slug>/', ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', ContentCategory.as_view(), name='category'),

    path('addpost/', AddPost.as_view(), name='add_post'),
    path('delete-post/<int:image_id>/', delete_post, name='delete_post'),

    path('saved-add/<int:image_id>/', saved_add, name='saved_add'),
    path('saved-remove/<int:image_id>/', saved_remove, name='saved_remove'),

    path('like/<int:image_id>/', like, name='like'),
    path('remove-like/<int:image_id>/', remove_like, name='remove-like'),

    path('comment/<slug:post_slug>/', AddComment.as_view(), name='comment'),

    path('FAQ/', FAQ.as_view(), name='faq'),
    path('FAQ/<int:answers_id>/', SelectAnswer.as_view(), name='answers'),
    path('FAQ/ask', AskQuestions.as_view(), name='ask'),

    # path('load_more_content/', load_more_content, name='load_more_content'),
]

users/urls.py
from django.urls import path
from .views import RegisterUser, logout_user, LoginUser, Messages, AddMessage, \
    Chat, ProfileUser, EditProfileUser, subscribe, unsubscribe, load_messages

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),

    path('messages/', Messages.as_view(), name='messages'),
    path('add_message/<slug:recipient>', AddMessage.as_view(), name='add-message'),
    path('chat/<slug:sender>/', Chat.as_view(), name='chat'),
    path('load_messages/', load_messages, name='load_messages'),


    path('edit/', EditProfileUser.as_view(), name='edit-profile'),
    path('<slug:username>/', ProfileUser.as_view(), name='profile'),

    path('subscribe/<slug:username>/', subscribe, name='subscribe'),
    path('unsubscribe/<slug:username>/', unsubscribe, name='unsubscribe'),
]

content/models.py
from django.db import models
from django.urls import reverse
from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="URL")
    img = models.ImageField(upload_to='Tag/&Y/%m/%d/', null=True, blank=True, verbose_name='Изображение')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})


class Content(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=255, verbose_name='Название')
    slug = models.SlugField(max_length=255, unique=True, verbose_name='URL')
    content = models.CharField(max_length=255, blank=True, null=True, verbose_name="Контент")
    image = models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name="Изображение")
    time_created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    time_updated = models.DateTimeField(auto_now=True, verbose_name="Дата редактирования")
    source_link = models.URLField(max_length=200, blank=True, null=True, verbose_name='Ссылка на источник')
    cat = models.ManyToManyField(Category, blank=True, verbose_name="Категории")
    likes = models.IntegerField(default=0, verbose_name="Понравилось")

    def get_vote_like(self):
        like = self.like_set.all()
        total_likes = like.count()
        self.likes = total_likes
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    class Meta:
        verbose_name = "изображение"
        verbose_name_plural = 'Изображении'
        ordering = ['-time_created']


class SavedImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.ForeignKey(Content, on_delete=models.CASCADE, related_name="saved_images", verbose_name="Изображение")
    create_database = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Пользователь {self.user} | Изображение {self.content.title} {self.content.id}'

    class Meta:
        unique_together = ('user', 'content')

        verbose_name = 'сохранённое изображение'
        verbose_name_plural = 'Сохранённые изображения'


class Questions(models.Model):
    PROBLEM = 0
    ERROR = 1
    IMPROVEMENT = 2

    TYPE = (
        (PROBLEM, 'Проблема регистрации/авторизации'),
        (ERROR, 'Ошибка при работе с сайтом'),
        (IMPROVEMENT, 'Предложения по улучшению'),
    )

    type = models.SmallIntegerField(default=PROBLEM, choices=TYPE, verbose_name='тип вопроса')
    title = models.CharField(default=None, max_length=255, verbose_name='Название')
    body = models.TextField(blank=True, null=True, verbose_name="Тело вопроса")
    email = models.EmailField(default=None, null=True, max_length=255, verbose_name='Почта')
    is_answered = models.BooleanField(default=False, verbose_name="Дан ответ")
    time_created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "вопрос"
        verbose_name_plural = 'Вопросы'
        ordering = ['-time_created']


class Answers(models.Model):
    title = models.CharField(default=None, max_length=255, verbose_name='Название')
    body = models.TextField(blank=True, verbose_name="Тело ответа")
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")
    time_created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    time_updated = models.DateTimeField(auto_now=True, verbose_name="Дата редактирования")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "ответ"
        verbose_name_plural = 'Ответы'
        ordering = ['-time_updated']


class Review(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    body = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Изображение {self.content.title} | комментарий от {self.owner.username}'

    class Meta:
        verbose_name = 'реакции / комментарии'
        verbose_name_plural = 'Реакция / Комментарий'


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # Ограничение на то, чтобы пользователь не мог лайкать один пост несколько раз
        unique_together = (('user', 'content'),)

content/forms.py
from django import forms
from .models import Review, Content, Questions


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = ['image', 'title', 'content', 'source_link', 'cat']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'source_link': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'class': 'form-input', 'rows': 10}),
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['body']

        widgets = {
            'body': forms.TextInput(attrs={'class': 'comment_input', 'placeholder': 'Добавить комментарий'}),
        }


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Questions
        fields = ['type', 'title', 'body', 'email']

        widgets = {
            # 'type': forms.Select(choices=[(key, value) for key, value in Questions.TYPE if key != Questions.PUBLISHED]),
            'title': forms.TextInput(attrs={'class': 'form-input', 'placeholder': "Вопроса"}),
            'body': forms.Textarea(attrs={'class': 'form-input', 'rows': 10, 'placeholder': "Расскажите подробнее"}),
            'email': forms.EmailInput(attrs={'class': 'form-input', 'placeholder': 'Укажите почту на которую вам отправить '
                                                                                   'ответ'}),
        }

content/templates/content/addpost.html
{% extends 'content/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/posts.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
{% if previous_page %}
<div class="previous_page">
    <a href="{{ previous_page }}" class="prev_page">
        <i class="fa-solid fa-arrow-left"></i>
    </a>
</div>
{% endif %}

<div class="add">
    <form action="{% url 'add_post' %}" method="post" enctype="multipart/form-data" class="add_post">
        <h1>{{ title }}</h1>
        {% csrf_token %}
        <div class="add_image">
            {{ form.image }}
            <label for="{{ form.image.id_for_label }}" class="file-label">Выберите изображение</label>
        </div>
        <div class="add_field">
            <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
            {{ form.title }}
        </div>
        <div class="add_field">
            <div class="toggle_content">
                <label for="{{ form.content.id_for_label }}">Добавить описание</label>
            </div>
            <div class="add_content">
                {{ form.content }}
            </div>
        </div>
        <div class="add_field">
            <label for="{{ form.source_link.id_for_label }}">{{ form.source_link.label }}</label>
            {{ form.source_link }}
        </div>
        <div class="add_field last">
            <p>Выберите теги</p>
            <div class="cat_selected">
                {{ form.cat }}
            </div>
        </div>
        <button class="add_btn">Добавить</button>
    </form>
</div>

<script src="{% static 'js/add_post.js' %}"></script>
{% endblock %}

content/templates/content/base.html
<!DOCTYPE html>
{% load static %}
{% load custom_query_transform %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pinfinity</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <!-- Favicon   -->
    <link type="Image/x-icon" href="{% static 'images/favicon.jpg'%}" rel="icon">
    <!-- base style -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <!-- Custom styles for this template -->
    {% block css %}{% endblock css %}
</head>
<body>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/navbarJs.js' %}"></script>
<header>
    <div class="navbar">
        <div class="logo">
            <a href="{% url 'index' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
        </div>
        <div class="post_links">
            <ul class="links">
                {% for m in menu %}
                {% if m.url_name == 'add_post' %}
                <li><a href="{% url m.url_name %}" class="action_btn">{{ m.title }}</a></li>
                {% elif m.url_name == 'faq' %}
                <div class="search_form">
                    <form id="search" class="form" action="{% url 'index' %}" method="get">
                        <div class="form-search">
                            <button type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                            <input class="search-ideas" type="text" name="search_query" placeholder="Поиск идей"
                                   value="{{ search_query }}"/>
                        </div>
                    </form>
                </div>
                <li><a href="{% url m.url_name %}">{{ m.title }}</a></li>
                {% elif m.title == 'Сообщения' %}
                <li class="chats">
                    <a href="{% url m.url_name %}"><i class="fa-solid fa-comment"></i></a>
                </li>
                {% elif m.title == 'Аккаунт' %}
                <li class="toggle_account">
                    <a href="{% url m.url_name request.user.username %}"><img src="{{ request.user.img.url }}" class="image"></a>
                </li>
                {% elif m.url_name == 'logout' %}
                <li class="logout">
                    <a href="{% url m.url_name %}"><i class="fa-solid fa-right-from-bracket"></i></a>
                </li>
                {% else %}
                <li><a href="{% url m.url_name %}">{{ m.title }}</a></li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="toggle_btn">
        <i class="fa-solid fa-bars"></i>
    </div>
    {% if request.user.is_authenticated %}
    <div class="dropdown_menu auth">
        {% else %}
        <div class="dropdown_menu">
            {% endif %}
            <ul class="links">
                {% for m in menu %}
                {% if m.url_name == 'profile' %}
                <li><a href="{% url m.url_name request.user.username %}">{{ m.title }}</a></li>
                {% else %}
                <li><a href="{% url m.url_name %}">{{ m.title }}</a></li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
</header>

<div class="content">
    <div class="wrap">
        {% if messages or form.errors %}
        {% if messages %}
        {% for message in messages %}
        <div id="alert-block" class="alert alert-{{message.tags}}" role="alert">
        {{ message }}
        {% endfor %}
        {% else %}
        <div id="alert-block-form" class="alert" role="alert">
        {{ form.errors }}
        {% endif %}
        </div>
        {% endif %}

        {% block content %}
        {% endblock %}

        {% if page_obj.has_other_pages %}
        <div class="pagination">
            <ul class="list-pages">
                {% if page_obj.has_previous %}
                <li class="page-num">
                    <a href="?{% query_transform request search_query=search_query page=page_obj.previous_page_number %}">&lt;</a>
                </li>
                {% endif %}

                {% for p in paginator.page_range %}
                {% if page_obj.number == p %}
                <li class="page-num page-num-selected">
                    <span>{{ p }}</span>
                </li>
                {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:+2 %}
                <li class="page-num">
                    <a href="?{% query_transform request search_query=search_query page=p %}">{{ p }}</a>
                </li>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-num">
                    <a href="?{% query_transform request search_query=search_query page=page_obj.next_page_number %}">&gt;</a>
                </li>
                {% endif %}
            </ul>
        </div>
        {% endif %}
    </div>
</div>
</body>
</html>

content/templates/content/faq.html
{% extends 'content/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/faq.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
<div class="faq">
    <div class="sidebar">
        <ul>
            {% for a in answers %}
            {% if a.pk == selected %}
            <li class="list-group selected">
                <p class="list-group-item">{{ a.title }}</p>
            </li>
            {% else %}
            <li class="list-group"><a href="{% url 'answers' a.id %}" class="list-group-item">{{ a.title }}</a></li>
            {% endif %}
            {% endfor %}
            <li class="list-group"><a href="{% url 'ask' %}" class="list-group-item add_questions">Задать вопрос</a></li>
        </ul>
    </div>
    <div class="faq_text">
        {% for a in answers %}
        {% if a.pk == selected %}
        <div class="faq_content selected">
        {% else %}
        <div class="faq_content">
        {% endif %}
        {{ a.body|safe }}
        </div>
        {% endfor %}
        {% if ask %}
        <div class="add">
            <form action="{% url 'ask' %}" method="post" class="add_question">
                <h1>{{ title }}</h1>
                {% csrf_token %}
                <div class="add_field">
                    <label for="{{ form.type.id_for_label }}">{{ form.type.label }}</label>
                    {{ form.type }}
                </div>
                <div class="add_field">
                    <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
                    {{ form.title }}
                </div>
                <div class="add_field">
                    <label for="{{ form.body.id_for_label }}">{{ form.body.label }}</label>
                    {{ form.body }}
                </div>
                <div class="add_field">
                    <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                    {{ form.email }}
                </div>
                <button class="add_btn">Отправить</button>
            </form>
        </div>
        {% endif %}
        </div>
    </div>
    {% endblock content %}

content/templates/content/index.html
{% extends 'content/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/posts.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
<div class="catbar">
    {% if selected == 0%}
    <h2>Выбрать категорию</h2>
    {% else %}
    <h2><a href="{% url 'index' %}">Открыть все категории</a></h2>
    {% endif %}
    <div class="toggle_cat">
        <i class="fa-solid fa-angle-up"></i>
    </div>
    <div class="midbar open">
        <ul>
            {% for cat in cats %}
            {% if cat.content__count > 0 %}
            {% if cat.pk == selected %}
            <li class="selected">
                <img src="{{ cat.img.url }}" alt="">
                <div class="cat_text">
                    <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                </div>
            </li>
            {% else %}
            <li>
                <a href="{{ cat.get_absolute_url }}"><img src="{{ cat.img.url }}" alt=""></a>
                <div class="cat_text">
                    <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                </div>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>
<div class="main">
    {% for post in posts %}
    <div class="card">
        <div class="pict">
            <a href="{{ post.get_absolute_url }}">
                <img src="{{ post.image.url }}" alt="image {{ post.title }}" class="image">
            </a>
        </div>
        <div class="post_owner">
            <img src="{{ post.owner.img.url }}" alt="image {{ post.owner.username }}" class="owner_image">
            <p>{{ post.owner.username }}</p>
        </div>
        <div class="details" onclick="window.location='{{ post.get_absolute_url }}'">
            <h2>{{ post.title|linebreaks|truncatewords:20 }}</h2>
            <div class="save_btn">
                {% if post.saved %}
                <a href="{% url 'saved_remove' post.id %}" class="btn saved">сохранено</a>
                {% else %}
                <a href="{% url 'saved_add' post.id %}" class="btn save">сохранить</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="loading-trigger"></div>
<!--<script src="{% static 'js/ajax.js' %}"></script>-->
{% endblock content %}

content/templates/content/post.html
{% extends 'content/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/posts.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
{% if previous_page %}
<div class="previous_page">
    <a href="{{ previous_page }}" class="prev_page">
        <i class="fa-solid fa-arrow-left"></i>
    </a>
</div>
{% endif %}

<div class="wrap_post">
    <div class="content_post">
        <div class="post">
            <div class="post_image">
                <img src="{{ post.image.url }}" alt="image {{ post.title }}" class="image">
            </div>
            <div class="post_text">
                <div class="save_btn save_post">
                    {% if post.owner == request.user %}
                    <a href="{% url 'delete_post' post.id %}" class="btn remove_post">удалить</a>
                    {% endif %}
                    {% if post.saved %}
                    <a href="{% url 'saved_remove' post.id %}" class="btn saved">сохранено</a>
                    {% else %}
                    <a href="{% url 'saved_add' post.id %}" class="btn save">сохранить</a>
                    {% endif %}
                </div>
                <div class="more_info">
                    {% if post.source_link %}
                    <a href="{{ post.source_link }}">Источник</a>
                    {% endif %}
                    {% if post.content %}
                    <div class="post_content">
                        <p class="text_content">Описание</p>
                        {{ post.content|linebreaks }}
                    </div>
                    {% endif %}
                </div>
                {% if post.owner %}
                <div class="container_owner">
                    <div class="owner">
                        <div class="owner_image">
                            <a href="{% url 'profile' post.owner.username %}">
                                <img src="{{ post.owner.img.url }}" alt="image {{ post.owner.username }}" class="image"></a>
                        </div>
                        <div class="owner_info">
                            <a href="{% url 'profile' post.owner.username %}">{{ post.owner.username }}</a>
                            <p>{{ subscribers_count }} подписчик</p>
                        </div>
                    </div>
                    {% if is_subscriber %}
                    <div class="owner knop">
                        <a href="{% url 'unsubscribe' post.owner.username %}" class="btn unsub">отписаться</a>
                    </div>
                    {% else %}
                    <div class="owner knop">
                        <a href="{% url 'subscribe' post.owner.username %}" class="btn sub">подписаться</a>
                    </div>
                    {% endif %}
                </div>
                {% endif %}
                <div class="cats">
                    <p class="text_content">Тэги</p>
                    <ul>
                        {% for cat in post.cat.all %}
                        <li>
                            <a href="{{ cat.get_absolute_url }}">#{{ cat.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="commentList">
                    <p class="text_content">Комментарии:</p>
                    {% if not post.review_set.all %}
                    <p>Здесь пока пусто</p>
                    {% endif %}
                    {% for comment in post.review_set.all %}
                    <div class="comment">
                        <div class="comment_owner">
                            <a href="{% url 'profile' comment.owner.username %}">
                                <img class="image" src="{{ comment.owner.img.url }}" alt="image {{ comment.owner.username }}"/>
                            </a>
                        </div>
                        <a href="{% url 'profile' comment.owner.username %}" class="comment_author">
                            {{ comment.owner.username }}</a>
                        <div class="comment_details">
                            <p class="comment_body">{{ comment.body|linebreaksbr }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
            <div class="form_comment">
                <span class="icon-like">
                    <p>{{ post.likes }}</p>
                    {% if post.liked %}
                    <a href="{% url 'remove-like' post.id %}"><i class="fa-solid fa-heart icn-like"></i></a>
                    {% else %}
                    <a href="{% url 'like' post.id %}"><i class="fa-regular fa-heart icn-like"></i></a>
                    {% endif %}
                </span>
                <form action="{% url 'comment' post.slug %}" method="POST">
                    {% csrf_token %}
                    <div class="form_field">
                        {% if request.user.is_authenticated %}
                        <div class="current_user">
                            <img src="{{ user.img.url }}" alt="image {{ user.username }}" class="image">
                        </div>
                        {% endif %}
                        {{ form_comment.body }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}