Pinfinity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import reverse_lazy
from users.views import CustomPasswordResetView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('content.urls')),
    path('profile/', include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('reset-password/', CustomPasswordResetView.as_view(), name='reset_password'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', CustomPasswordResetCompleteView.as_view(
        template_name='users/reset_password_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterUser, logout_user, LoginUser, Messages, AddMessage, \
    Chat, ProfileUser, EditProfileUser, subscribe, unsubscribe, load_messages

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),

    path('messages/', Messages.as_view(), name='messages'),
    path('add_message/<slug:recipient>', AddMessage.as_view(), name='add-message'),
    path('chat/<slug:sender>/', Chat.as_view(), name='chat'),
    path('load_messages/', load_messages, name='load_messages'),


    path('edit/', EditProfileUser.as_view(), name='edit-profile'),
    path('<slug:username>/', ProfileUser.as_view(), name='profile'),

    path('subscribe/<slug:username>/', subscribe, name='subscribe'),
    path('unsubscribe/<slug:username>/', unsubscribe, name='unsubscribe'),
]

content/models.py
from django.db import models
from django.urls import reverse
from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="URL")
    img = models.ImageField(upload_to='Tag/&Y/%m/%d/', null=True, blank=True, verbose_name='Изображение')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})


class Content(models.Model):
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=255, verbose_name='Название')
    slug = models.SlugField(max_length=255, unique=True, verbose_name='URL')
    content = models.CharField(max_length=255, blank=True, null=True, verbose_name="Контент")
    image = models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name="Изображение")
    time_created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    time_updated = models.DateTimeField(auto_now=True, verbose_name="Дата редактирования")
    source_link = models.URLField(max_length=200, blank=True, null=True, verbose_name='Ссылка на источник')
    cat = models.ManyToManyField(Category, blank=True, verbose_name="Категории")
    likes = models.IntegerField(default=0, verbose_name="Понравилось")

    def get_vote_like(self):
        like = self.like_set.all()
        total_likes = like.count()
        self.likes = total_likes
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    class Meta:
        verbose_name = "изображение"
        verbose_name_plural = 'Изображении'
        ordering = ['-time_created']


class SavedImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.ForeignKey(Content, on_delete=models.CASCADE, related_name="saved_images", verbose_name="Изображение")
    create_database = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Пользователь {self.user} | Изображение {self.content.title} {self.content.id}'

    class Meta:
        unique_together = ('user', 'content')

        verbose_name = 'сохранённое изображение'
        verbose_name_plural = 'Сохранённые изображения'


class Questions(models.Model):
    PROBLEM = 0
    ERROR = 1
    IMPROVEMENT = 2

    TYPE = (
        (PROBLEM, 'Проблема регистрации/авторизации'),
        (ERROR, 'Ошибка при работе с сайтом'),
        (IMPROVEMENT, 'Предложения по улучшению'),
    )

    type = models.SmallIntegerField(default=PROBLEM, choices=TYPE, verbose_name='тип вопроса')
    title = models.CharField(default=None, max_length=255, verbose_name='Название')
    body = models.TextField(blank=True, null=True, verbose_name="Тело вопроса")
    email = models.EmailField(default=None, null=True, max_length=255, verbose_name='Почта')
    is_answered = models.BooleanField(default=False, verbose_name="Дан ответ")
    time_created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "вопрос"
        verbose_name_plural = 'Вопросы'
        ordering = ['-time_created']


class Answers(models.Model):
    title = models.CharField(default=None, max_length=255, verbose_name='Название')
    body = models.TextField(blank=True, verbose_name="Тело ответа")
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")
    time_created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    time_updated = models.DateTimeField(auto_now=True, verbose_name="Дата редактирования")

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = "ответ"
        verbose_name_plural = 'Ответы'
        ordering = ['-time_updated']


class Review(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    body = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Изображение {self.content.title} | комментарий от {self.owner.username}'

    class Meta:
        verbose_name = 'реакции / комментарии'
        verbose_name_plural = 'Реакция / Комментарий'


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # Ограничение на то, чтобы пользователь не мог лайкать один пост несколько раз
        unique_together = (('user', 'content'),)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import CreateView, ListView, UpdateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login, logout
from django.urls import reverse_lazy, resolve
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.contrib.auth import views as auth_views
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.db.models import Q, Subquery, OuterRef

from .forms import RegisterUserForm, UserProfileForm, MessageForm
from .models import Message, User, Subscription
from content.models import Content
from content.utils import DataMixin


class ProfileUser(DataMixin, ListView):
    model = User
    template_name = 'users/profile.html'
    slug_url_kwarg = 'username'
    context_object_name = 'user'

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs['username'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        previous_page = self.request.META.get('HTTP_REFERER')
        user = self.get_object()
        c_def = self.get_user_context()

        saved_posts_user = Content.objects.filter(saved_images__user__username=self.kwargs['username'])
        subscribers_count = Subscription.objects.count_subscribers(user)

        context.update({'user': user, 'saved_posts': saved_posts_user, 'subscribers_count': subscribers_count,
                        'previous_page': previous_page})

        if self.request.user.is_authenticated:
            saved_current_user = Content.objects.filter(saved_images__user=self.request.user)
            is_subscriber = Subscription.objects.is_subscriber(self.request.user, user)
            context.update({'saved_current': saved_current_user, 'is_subscriber': is_subscriber})

        return dict(list(context.items()) + list(c_def.items()))


class EditProfileUser(LoginRequiredMixin, DataMixin, UpdateView):
    form_class = UserProfileForm
    template_name = 'users/edit_profile.html'
    login_url = reverse_lazy('login')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        c_def = self.get_user_context(title='Изменение профиля')
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        super().form_valid(form)
        messages.success(self.request, 'Данные были успешно изменены.')
        return super().form_valid(form)


class Messages(LoginRequiredMixin, DataMixin, ListView):
    model = Message
    template_name = 'users/message.html'
    login_url = reverse_lazy('index')
    context_object_name = 'message'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()

        count_unread_messages = Message.objects.count_unread_messages(self.request.user)
        context['unread_messages'] = count_unread_messages

        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        # Подзапрос для получения последних сообщений для каждого отправителя
        latest_messages_subquery = Message.objects.filter(
            recipient=self.request.user,
            sender=OuterRef('sender')
        ).order_by('-created').values('created')[:1]

        # Основной запрос, который выбирает сообщения, удовлетворяющие подзапросу
        queryset = Message.objects.filter(
            recipient=self.request.user,
            created=Subquery(latest_messages_subquery)
        ).select_related('sender').order_by('is_read', '-created')

        return queryset


class Chat(LoginRequiredMixin, DataMixin, ListView):
    model = Message
    template_name = 'users/chat.html'
    context_object_name = 'message'
    # временно, пока не разобрался с Ajax
    paginate_by = 9999

    def get_login_url(self):
        # Используйте resolve_url для динамического sender
        return reverse_lazy('profile', kwargs={'username': self.kwargs['sender']})

    def dispatch(self, request, *args, **kwargs):
        # Проверяем, был ли пользователь перенаправлен из-за отсутствия аутентификации
        if not request.user.is_authenticated:
            messages.error(request, f'Для того чтобы написать {self.kwargs["sender"]} нужно авторизоваться')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        previous_page = self.request.META.get('HTTP_REFERER')
        context['previous_page'] = previous_page

        c_def = self.get_user_context(form=MessageForm(), sender=self.kwargs['sender'])
        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        user = self.request.user
        sender = User.objects.get(username=self.kwargs['sender'])
        queryset = Message.objects.filter(
            Q(recipient__username=user, sender__username=sender) |
            Q(recipient__username=sender, sender__username=user)
        ).select_related('sender', 'recipient')

        Message.objects.mark_messages_as_read(sender=sender, recipient=user)
        return queryset


class AddMessage(LoginRequiredMixin, CreateView):
    form_class = MessageForm
    template_name = 'users/chat.html'
    login_url = reverse_lazy('login')

    def form_valid(self, form):
        try:
            message = form.save(commit=False)
            message.sender = self.request.user
            message.recipient = User.objects.get(username=self.kwargs['recipient'])
            print(message.recipient)
            print(message.sender)
            message.save()
            return redirect(self.request.META.get('HTTP_REFERER'))
        except Exception as e:
            error_message = f"Ошибка сохранения данных: {str(e)}"
            return HttpResponse(error_message)


def load_messages(request):
    sender = str(request.GET.get('sender_username', False))
    messages = Message.objects.filter(recipient__username=request.user,
                                      sender__username=sender).select_related('sender', 'recipient')
    data = [{'body': message.body, 'created': message.created, 'sender': message.sender.username} for message in messages]
    return JsonResponse({'messages': data})


class LoginUser(DataMixin, LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Авторизация')
        return dict(list(context.items()) + list(c_def.items()))


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Регистрация')

        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('index')


def logout_user(request):
    logout(request)
    return redirect('index')


# Логика подписки / отписки
def subscribe(request, username):
    current_page = request.META.get('HTTP_REFERER')
    user = request.user

    if user.is_anonymous:
        messages.error(request, 'Для подписки необходимо авторизоваться')
    elif username == user.username:
        messages.error(request, 'Нельзя подписаться на самого себя')
    else:
        target_user = User.objects.get(username=username)
        subscriber = Subscription.objects.filter(subscriber=user, target_user=target_user)
        if not subscriber.exists():
            Subscription.objects.create(subscriber=user, target_user=target_user)
    return redirect(current_page)


def unsubscribe(request, username):
    current_page = request.META.get('HTTP_REFERER')
    user = request.user
    if user.is_anonymous:
        messages.error(request, 'Для подписки необходимо авторизоваться')

    else:
        target_user = User.objects.get(username=username)
        subscriber = Subscription.objects.filter(subscriber=user, target_user=target_user)
        if subscriber.exists():
            subscriber.delete()
    return redirect(current_page)


# Страницы восстановления пароля
class CustomPasswordResetView(DataMixin, auth_views.PasswordResetView):
    template_name = 'users/reset_password.html'
    success_url = reverse_lazy("login")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()

        return dict(list(context.items()) + list(c_def.items()))


class CustomPasswordResetConfirmView(DataMixin, auth_views.PasswordResetConfirmView):
    template_name = 'users/reset.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()

        return dict(list(context.items()) + list(c_def.items()))


class CustomPasswordResetCompleteView(DataMixin, auth_views.PasswordResetCompleteView):
    template_name = 'users/reset_password_complete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()

        return dict(list(context.items()) + list(c_def.items()))

users/templates/users/chat.html
{% extends 'content/base.html' %}
{% load static %}
{% load humanize %}
{% block css %}
<link href="{% static 'css/messages.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
{% if previous_page %}
<div class="previous_page">
    <a href="{{ previous_page }}" class="prev_page">
        <i class="fa-solid fa-arrow-left"></i>
    </a>
</div>
{% endif %}

<div class="wrap_post">
    <div class="content_post">
        <h1>Чат с пользователем {{ sender }}</h1>
        <div class="chat">
            {% for mes in message %}
            {% if mes.sender == request.user %}
            <div class="mess right">
            {% else %}
            <div class="mess left">
            {% endif %}
                <span>{{ mes.created|naturalday }}</span>
                {{ mes.body }}
            </div>
            {% endfor %}
        </div>
        <form action="{% url 'add-message' sender %}" enctype="multipart/form-data" id="message-form" method="post">
            {% csrf_token %}
            {{ form.body }}
            <button><i class="fa-solid fa-paper-plane"></i></button>
        </form>
    </div>
</div>
<script src="{% static 'js/ajax.js' %}"></script>
{% endblock %}

users/templates/users/edit_profile.html
{% extends 'content/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
<div class="edit">
    <form action="{% url 'edit-profile' %}" method="post" class="add_post" enctype="multipart/form-data">
        <div class="first">
            <div class="user_image">
                <img src="{{ user.img.url }}" alt="{{ user.username }}" class="image">
            </div>
            <label for="{{ form.img.id_for_label }}" class="file-label">Выберите изображение</label>
            <div class="add_image">
                {{ form.img }}
            </div>
        </div>
        <div class="second">
            <h1>{{ title }}</h1>
            {% csrf_token %}
            <div class="add_field">
                <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                {{ form.username }}
            </div>
            <div class="add_field">
                <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
                {{ form.first_name }}
            </div>
            <div class="add_field">
                <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                {{ form.email }}
            </div>
            <div class="add_field">
                <label for="{{ form.source_link.id_for_label }}">{{ form.source_link.label }}</label>
                {{ form.source_link }}
            </div>
        </div>
        <button class="add_btn">Сохранить</button>
    </form>
</div>

{% endblock content %}

users/templates/users/login.html
{% extends 'content/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/loginPage.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
<!-- Авторизация -->
<section class="back">
    <div class="wrapper">
    <span class="icon-close">
        <a href="{% url 'index' %}">
            <i class="fa-solid fa-xmark icn-close"></i>
        </a>
    </span>
        <div class="form-box login">
            <h2>Авторизация</h2>
            <form method="post">
                {% csrf_token %}
                <div class="input-box">
                    <span class="icon">
                        <i class="fa-solid fa-envelope icn"></i>
                    </span>
                    <input type="text" name="username" required>
                    <label>Логин</label>
                </div>
                <div class="input-box">
                    <span class="icon">
                        <i class="fa-solid fa-lock"></i>
                    </span>
                    <input type="password" name="password" required>
                    <label>Пароль</label>
                </div>
                <div class="remember-forgot">
                    <a href="{% url 'reset_password' %}">Забыли пароль?</a>
                </div>
                <button type="submit" class="btn">Войти</button>
                <div class="login-register">
                    <p><a href="{% url 'register' %}" class="register-link">Создать аккаунт</a></p>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

users/templates/users/message.html
{% extends 'content/base.html' %}
{% load static %}
{% load humanize %}
{% block css %}
<link href="{% static 'css/messages.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
<!-- Main Section -->
<main class="inbox">
    <div class="content-box">
        <h3 class="inbox__title">Новых сообщений: (<span>{{ unread_messages }}</span>)</h3>
        <ul class="messages">
            {% for mes in message %}
            {% if mes.is_read %}
            <li class="message">
            {% else %}
            <li class="message message--unread">
            {% endif %}
                <div class="sender_image">
                    <a href="#"><img src="{{ mes.sender.img.url }}" class="image"></a>
                </div>
                <div class="message_text">
                    <a href="{{ mes.get_absolute_url }}">
                        <div class="header_message">
                            <span class="message__author">{{ mes.sender.username }}</span>
                            <span class="message__date">{{ mes.created|naturalday }}</span>
                        </div>
                        <span class="message__body">{{ mes.body|slice:50 }}</span>
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</main>

{% endblock content %}

users/templates/users/profile.html
{% extends 'content/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
<link href="{% static 'css/posts.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}

{% if previous_page %}
<div class="previous_page">
    <a href="{{ previous_page }}" class="prev_page">
        <i class="fa-solid fa-arrow-left"></i>
    </a>
</div>
{% endif %}

<div class="user">
    <div class="user_image">
        <img src="{{ user.img.url }}" alt="{{ user.username }}" class="image">
    </div>
    <div class="username">@{{ user.username }}</div>
    {% if user.first_name %}
    <div class="name">Имя: {{ user.first_name }}</div>
    {% else %}
    <div class="name">Имя: Инкогнито</div>
    {% endif %}
    {% if user.source_link %}
    <div class="name">
        <a href="{{ user.source_link }}" target="_blank">Ссылка на контент пользователя</a>
    </div>
    {% endif %}
    <div class="subs">{{ subscribers_count }} подписчиков</div>
    {% if user == request.user %}
    <div class="change_profile">
        <a href="{% url 'edit-profile' %}" class="btn change">изменить профиль</a>
    </div>
    {% else %}
    <div class="interaction">
        <div class="change_profile knop">
            <a href="{% url 'chat' user.username %}" class="btn mes">написать</a>
        </div>
        <div class="change_profile knop">
            {% if is_subscriber %}
            <a href="{% url 'unsubscribe' user.username %}" class="btn unsub">отписаться</a>
            {% else %}
            <a href="{% url 'subscribe' user.username %}" class="btn sub">подписаться</a>
            {% endif %}
        </div>
    </div>
    {% endif %}
    <div class="users_content">
        <div class="create active">Созданные</div>
        <div class="saved">Сохраненные</div>
    </div>
</div>
<div class="users_main">
    <div class="content-c active">
        {% if not user.content_set.all %}
        <div class="text">
            {% if user == request.user %}
            <p>Здесь пока ничего нет. Тут будут отображаться изображения, которые вы создадите.</p>
            <div class="button">
                <a href="{% url 'add_post' %}">Создать идею</a>
            </div>
            {% else %}
            <p>Здесь пока ничего нет. Тут будут отображаться изображения, которые {{user.username}} создаст</p>
            {% endif %}
        </div>
        {% else %}
        <div class="create_post">
            {% for post in user.content_set.all %}
            <div class="card">
                <div class="pict">
                    <a href="{{ post.get_absolute_url }}">
                        <img src="{{ post.image.url }}" alt="image {{ post.title }}" class="image">
                    </a>
                </div>
                <div class="post_owner">
                    <img src="{{ post.owner.img.url }}" alt="image {{ post.owner.username }}" class="owner_image">
                    <p>{{ post.owner.username }}</p>
                </div>
                <div class="details" onclick="window.location='{{ post.get_absolute_url }}'">
                    <h2>{{ post.title|linebreaks|truncatewords:20 }}</h2>
                    <div class="save_btn">
                        {% if post in saved_current %}
                        <a href="{% url 'saved_remove' post.id %}" class="btn saved">сохранено</a>
                        {% else %}
                        <a href="{% url 'saved_add' post.id %}" class="btn save">сохранить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <div class="content-s">
        {% if not saved_posts %}
        <div class="text">
            {% if user == request.user %}
            <p>Здесь пока ничего нет. Тут будут отображаться изображения, которые вы сохраните.</p>
            <div class="button">
                <a href="{% url 'index' %}">Найти идею</a>
            </div>
            {% else %}
            <p>Здесь пока ничего нет. Тут будут отображаться изображения, которые {{user.username}} сохранит.</p>
            {% endif %}
        </div>
        {% else %}
        <div class="saved_post">
            {% for post in saved_posts %}
            <div class="card">
                <div class="pict">
                    <a href="{{ post.content.get_absolute_url }}">
                        <img src="{{ post.image.url }}" alt="image {{ post.title }}" class="image">
                    </a>
                </div>
                <div class="post_owner">
                    <img src="{{ post.owner.img.url }}" alt="image {{ post.owner.username }}" class="owner_image">
                    <p>{{ post.owner.username }}</p>
                </div>
                <div class="details" onclick="window.location='{{ post.get_absolute_url }}'">
                    <h2>{{ post.title|linebreaks|truncatewords:20 }}</h2>
                    <div class="save_btn">
                        {% if post in saved_current %}
                        <a href="{% url 'saved_remove' post.id %}" class="btn saved">сохранено</a>
                        {% else %}
                        <a href="{% url 'saved_add' post.id %}" class="btn save">сохранить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>

</div>
<script src="{% static 'js/profile.js' %}"></script>
{% endblock %}

users/templates/users/register.html
{% extends 'content/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/loginPage.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
<!-- Регистрация -->
<section class="back">
    <div class="wrapper active">
    <span class="icon-close">
    <a href="{% url 'index' %}">
        <i class="fa-solid fa-xmark icn-close"></i>
    </a>
    </span>
        <div class="form-box register">
            <h2>Регистрация</h2>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="input-box">
                <span class="icon">
                {% if field.label == 'Почта' %}
                    <i class="fa-solid fa-envelope"></i>
                {% elif field.label == 'Имя пользователя' %}
                    <i class="fa-solid fa-user"></i>
                {% elif field.label == 'Пароль' %}
                    <i class="fa-solid fa-lock"></i>
                {% elif field.label == 'Подтверждение пароля' %}
                    <i class="fa-solid fa-lock"></i>
                {% endif %}
                </span>
                    {{ field }}
                    <label>{{ field.label }}</label>
                    {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
                <div class="remember-forgot">
                    <label><input type="checkbox">Я согласен с правилами и условиями</label>
                </div>
                <button type="submit" class="btn">Регистрация</button>
                <div class="login-register">
                    <p>Уже есть аккаунт? <a href="{% url 'login' %}" class="login-link">Войти</a></p>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

users/templates/users/reset.html
{% extends 'content/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/reset.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
<div class="card">
    <div class="card-header"><h3 class="text">Введите новый пароль</h3>
    </div>
    <div class="card-body">
        <p>Пожалуйста, введите новый пароль дважды, чтобы мы могли убедиться в правильности написания.</p>
    </div>
    <div class="card-form">
        <form class="form" method="post">
            <div class="form__field">
                {% csrf_token %}
                <p>{{ form.new_password1.label }}</p>
                <p>{{ form.new_password1 }}</p>
                <p>{{ form.new_password2.label }}</p>
                <p>{{ form.new_password2 }}</p>
            </div>
            <input type="submit" value="Изменить мой пароль" class="button">
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/reset_password_complete.html
{% extends 'content/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/reset.css' %}" rel="stylesheet">
{% endblock css %}
{% block content %}
<div class="card">
    <div class="card-header"><h3 class="text">Восстановление пароля завершено</h3>
    </div>
    <div class="card-body">
        <p>Ваш пароль был сохранен. Теперь вы можете войти.</p>
    </div>
    <div class="card-footer">
        <div class="small"><a href="{% url 'login' %}" class="button">Войти</a></div>
    </div>
</div>
{% endblock %}